// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQYjWUNqgOCQJvgYiWQQCaQ6dylNkE_dE',
    appId: '1:995376568207:android:6daa7f27c157c973331dfa',
    messagingSenderId: '995376568207',
    projectId: 'g0lineapi-opxykx',
    databaseURL: 'https://g0lineapi-opxykx.firebaseio.com',
    storageBucket: 'g0lineapi-opxykx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUdJWB3EBhM1GS9x8J0Xa0e3-DubX8M68',
    appId: '1:995376568207:ios:da47dfad1ad540e1331dfa',
    messagingSenderId: '995376568207',
    projectId: 'g0lineapi-opxykx',
    databaseURL: 'https://g0lineapi-opxykx.firebaseio.com',
    storageBucket: 'g0lineapi-opxykx.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuthApp',
  );
}
